name: Cathy Wise
markdown: redcarpet
pygments: true
description:      Comings and Goings
disqus_shortname: cathywise
url:              http://localhost:4000
title: Cathy Wise
# Owner/author information
owner:
  name:           Cathy Wise
  avatar:         me-pixeld.jpg
  bio:            "Software developer, hobby collector."
  disclaimer:     "All opinions on this site are my own and not my employer's etc."
  #email:          you@email.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        everbloom
  github:         lupiter
  stackexchange:  912607/cathy
  instagram:      everbloom
  flickr:         44632322@N00
  tumblr:         everbloom
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/113703753421537375035

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-47476877-1

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: ThreeSides
    url: /threesides/
  - title: Blog
    url: /blog/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Australia/Canberra
future:      true
pygments:    true
